---
kind: auto.CommandConfig
name: build
spec:
  disableImage: true
---
kind: auto.CustomSteps
spec:
  steps:
    - name: dev-server
      toplevel: true
---
kind: custom.Step
name: dev-server
spec:
  makefile:
    enabled: true
    phony: true
    script:
      - hack/dev-server.sh
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    linux-armv7:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
    darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
    windows-amd64.exe:
      GOOS: windows
      GOARCH: amd64
---
kind: golang.Protobuf
spec:
  specs:
    - source: api/socket/message.proto
      subdirectory: socket/message/
    - source: api/common/theila.proto
      subdirectory: common
    - source: api/rpc/resource.proto
      subdirectory: rpc
      genGateway: true
    - source: api/rpc/context.proto
      subdirectory: rpc
      genGateway: true
    - source: api/rpc/management.proto
      subdirectory: rpc
      genGateway: true
    - source: https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/status.proto
      subdirectory: google/rpc/
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/common/common.proto
      subdirectory: common/
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/resource/resource.proto
      subdirectory: talos/resource/
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/machine/machine.proto
      subdirectory: talos/machine/
      genGateway: true
    - source: https://raw.githubusercontent.com/cosi-project/runtime/master/api/v1alpha1/state.proto
      subdirectory: v1alpha1
      genGateway: true
    - source: https://raw.githubusercontent.com/cosi-project/runtime/master/api/v1alpha1/resource.proto
      subdirectory: v1alpha1
      genGateway: true
---
kind: js.Protobuf
spec:
  destinationRoot: src/api
  specs:
    - source: api/common/theila.proto
      subdirectory: common
      genGateway: true
    - source: api/socket/message.proto
      subdirectory: socket
    - source: api/rpc/resource.proto
      subdirectory: rpc
      genGateway: true
    - source: api/rpc/context.proto
      subdirectory: rpc
      genGateway: true
    - source: api/rpc/management.proto
      subdirectory: rpc
      genGateway: true
    - source: https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/status.proto
      subdirectory: google/rpc/
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/resource/resource.proto
      subdirectory: talos/resource
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/machine/machine.proto
      subdirectory: talos/machine
      genGateway: true
    - source: https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/any.proto
      subdirectory: google/protobuf/
      genGateway: true
    - source: https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/duration.proto
      subdirectory: google/protobuf/
      genGateway: true
    - source: https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/empty.proto
      subdirectory: google/protobuf/
      genGateway: true
    - source: https://raw.githubusercontent.com/protocolbuffers/protobuf/master/src/google/protobuf/timestamp.proto
      subdirectory: google/protobuf/
      genGateway: true
    - source: https://raw.githubusercontent.com/googleapis/googleapis/master/google/rpc/code.proto
      subdirectory: google/rpc/
      genGateway: true
    - source: https://raw.githubusercontent.com/siderolabs/talos/master/api/common/common.proto
      subdirectory: common/
      genGateway: true
    - source: https://raw.githubusercontent.com/cosi-project/runtime/master/api/v1alpha1/resource.proto
      subdirectory: v1alpha1
      genGateway: true
